language: ruby
rvm:
  - 2.4.0
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --alt-ignore '/.*/'  --disable-external --check-html --assume-extension 
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false


