language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --alt-ignore '/.*/'  --disable-external --check-html --assume-extension --file-ignore './_site/events/index.html'
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false


