language: ruby
cache: bundler
rvm:
  - 2.4.1
script:
  - bundle exec jekyll build --incremental
  - bundle exec htmlproofer ./_site --only-4xx  --disable-external --check-html --assume-extension 
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false


